#Location: ~/.config/starship.toml
#What_is_starship: https://starship.rs/

add_newline = false
command_timeout = 2000

format = """$username$directory$git_branch$git_status$character
"""

[character]
success_symbol = '[ ➜](bold green)'
error_symbol = '[ ➜](bold red)'

#warp-Drop ugly default prompt characters
#success_symbol = ""
#error_symbol = ""

# Shows the username
[username]
style_user = "yellow bold"
style_root = "black bold"
format = '[\[$user\]](#2883ff)' # 2883ff
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = "[$hostname](bold blue) "
disabled = false

# Shows current directory
[directory]
truncation_length = 0
truncation_symbol = "…/"
home_symbol = "~"
read_only_style = "197 bold"
read_only = '[]'
format = '[\[$path\]]($style)[$read_only]($read_only_style)'
style = "yellow bold"


# Shows current git branch
[git_branch]
always_show_remote = true
symbol = '\['
format = '[$symbol ($remote_name/)$branch]($style)'
style = "bold green"

# Shows current git status
[git_status]
#disabled = false
format = '[ $all_status$ahead_behind\]]($style)'
style = "bold green"
conflicted = "🏳"
up_to_date = ""
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = "[++($count)](green)"
renamed = "襁 "
deleted = " "



# Shows kubernetes context and namespace
[kubernetes]
format = "via [󱃾 $context($namespace)](bold purple) "
disabled = true

# ---

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
disabled = true
symbol = "󰌠"
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
format = "[//](black bold) [${symbol} ${pyenv_prefix}(${version} )(($virtualenv) )]($style) "


[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
